### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by DillonFlohr** [anthonyjclark/editor#1]
The Readme has the following text under the Editor heading:

`A GitHub App built with Probot that An app for checking grammar and spelling in GitHub pull requests.`

Perhaps it is intended to be 

`A GitHub App built with Probot that checks grammar and spelling in GitHub pull requests.`

**Comment by DillonFlohr** [comment]
Seems like a nice tool by the way!

**Comment by anthonyjclark** [comment]
Submit a PR. I'm sure you have a ton of free time  these days :)

**Comment by DillonFlohr** [comment]
Fixed by #2
